### ISSUE TITLE
Seems to get hung up on load screen occasionally

### ISSUE THREAD

**Issue by adamgins** [jamielob/reloader#12] opened 2016-11-13 21:54 UTC
Thanks for the package

Having some intermittent issues when I restarting, that app seems to get hung on the load screen. I have only seen this a few times.

As it's happening on mobile I don't really have much in the way of debug screens and have not managed to replicate when hooked up to XCode.

I was using this config:

```
Reloader.configure({
    check: 'everyStart', // Check for new code every time the app starts
    checkTimer: 3000,  // Wait 3 seconds to see if new code is available
    refresh: 'startAndResume', // Refresh to already downloaded code on both start and resume
    idleCutoff: 1000 * 60 * 10  // Wait 10 minutes before treating a resume as a start
}); 
```

Any thoughts pls?

**Comment by lorensr** [comment] 2016-11-13 23:37
Just published version 1.2.3. Try updating to it, and afterward if it
continues, let us know if you notice a common circumstance, thanks!

**Comment by adamgins** [comment] 2016-11-14 05:01
@lorensr thanks. Will try this out and let you know.
Any hints on debugging so I can see what's going on and get you better debug info?

**Comment by lorensr** [comment] 2016-11-14 05:14
The code's pretty small, you could clone it to yourapp/packages/reloader
and add console.logs

**Comment by adamgins** [comment] 2016-11-14 06:12
@lorensr thanks. I have not installed the code yet and I have not seen a "hang" yet. So far it seems to be working pretty well... but a bit scared to put it into production after the hang earlier today. 

I tried to check the code here to see what had changed but could not see anything recently. Anything to give me a bit more confidence, pls?

**Comment by lorensr** [comment] 2016-11-14 16:53
It was the change made in the last merged PR

**Comment by adamgins** [comment] 2016-11-14 18:35
Thanks. Ok I have put into production. So far so good.

**Comment by adamgins** [comment] 2016-11-16 09:32
I was out and about this morning and did get a whitescreen of death. As it was on physical phone it was hard to diagnose. Any thoughts?

I had not seen a whitescreen that persisted on the screen for 20+ seconds with my app before installing this package

**Comment by lorensr** [comment] 2016-11-16 19:58
Hey, I'm sorry to hear that. Not sure what it could be – I think the only
things this package does is reload and show/hide the launch screen, neither
of which should result in a permanent white screen. If can't reproduce
locally with `meteor run ios-device`, could point it at your production
domain, maybe while deploying new version.

**Comment by adamgins** [comment] 2016-11-16 21:19
@lorensr thanks. Yep I test with a production domain and have not replicated that issue with either my phone or emulator connected to XCode. It just happened when out and about and I opened the app. It could have hit low/bad mobile coverage

**Comment by adamgins** [comment] 2016-11-19 04:46
@lorensr just wondering if you have see White Screen of Death at all.. the app never recovers and only way to rectify it is to close (flick) the app.
 https://github.com/jamielob/reloader/issues/6#issuecomment-261642492

**Comment by lorensr** [comment] 2016-11-19 16:11
Vague memory of it happening in dev over a year ago. Couldn't reproduce and
didn't have users say they ran into it

**Comment by jamielob** [comment] 2017-01-25 11:16
@adamgins - I'm closing this issue since it's been dormant for a while but feel free to comment with an update.

**Closed as completed by jamielob** 2017-01-25 11:16 UTC

**Comment by sferoze** [comment] 2017-03-12 20:27
@jamielob 

I seem to be having this issue as well. I'm trying to make some adjustments to my settings to resolve it. Can you verify that I am using the code below correctly? What I am looking to do is set reloader to only refresh automatically on `firstStart`. Then notice the Tracker.autorun code. Basically I am instantly reloading the app like the default Meteor behavior, but I am doing it manually because I want to briefly show a screen that says "Updating" before reloading.  Is this correct way of achieving this?

```javascript
if (Meteor.isCordova) {
  if (Meteor.isDevelopment) {
    Reloader.configure({
      check: false,
      refresh: 'instantly'
    });
  } else {
    Reloader.configure({
      check: 'firstStart',
      checkTimer: 3000,
      refresh: 'start'
    });
  }

  Meteor.startup(function() {
    Meteor.setTimeout(function() {
      Tracker.autorun(function() {
        var updateAvailable;
        updateAvailable = Reloader.updateAvailable.get();
        if (updateAvailable) {
          Blaze.render(Template.starterLoader, $('body')[0]);
          Meteor.setTimeout(function() {
            return Reloader.reload();
          }, 1700);
        }
        return updateAvailable;
      });
    }, 5000);
  });
}
```

**Comment by jamielob** [comment] 2017-03-13 18:14
@sferoze - TBH I haven't used this package myself for a long time now! 

Why do you need the autorun block? You've set the package to refresh on start which means `Only refresh to already downloaded code on a start and not a resume`.
