### ISSUE TITLE
Reload doesn't work on "START"

### ISSUE THREAD

**Issue by nazarposhta** [jamielob/reloader#14] opened 2017-01-19 11:54 UTC
Hi everyone! I just tried to use this package for our app and I want to configure => "Update app on Start" but it doesn't work for some reason.
my code is just from example.

`Reloader.configure({`
`check: 'everyStart', // Check for new code every time the app starts`
`checkTimer: 3000,  // Wait 3 seconds to see if new code is available`
`refresh: 'startAndResume', // Refresh to already downloaded code on both start and resume`
`idleCutoff: 1000 * 60 * 10  // Wait 10 minutes before treating a resume as a start`
`});`

So it works on "Resume" but after app was started I still see the message "Please update" which I implemented, and old version on the phone. 
What to do with that?

**Comment by jamielob** [comment] 2017-01-22 02:25
Hi @nazarposhta - so it's downloading the update on first start and the refreshing the next time?  If so that's the intended result.

**Comment by nazarposhta** [comment] 2017-01-22 07:31
Exactly. On the next time.

**Comment by nazarposhta** [comment] 2017-01-22 07:32
I thought that it will be in the same time.

**Comment by jamielob** [comment] 2017-01-25 11:15
First time it loads it downloads the update and holds it ready for the next restart.  I'm going to close the issue for now since this behavior is by design.

**Closed as completed by jamielob** 2017-01-25 11:15 UTC
